version: "3.8"

services:
  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: wellness-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-wellness-events}
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - wellness-network

  # Express API Server
  server:
    build:
      context: ..
      dockerfile: infra/Dockerfile.server
    container_name: wellness-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-5000}
      MONGODB_URI: ${MONGODB_URI:-mongodb://admin:password@mongo:27017/wellness-events?authSource=admin}
      CLIENT_URL: ${CLIENT_URL:-http://localhost:3000}
      JWT_SECRET: ${JWT_SECRET:-dev-secret-key}
    depends_on:
      - mongo
    volumes:
      - ../server:/app/server
      - /app/server/node_modules
    networks:
      - wellness-network

  # React Client
  client:
    build:
      context: ..
      dockerfile: infra/Dockerfile.client
    container_name: wellness-client
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - wellness-network

volumes:
  mongo_data:
    driver: local

networks:
  wellness-network:
    driver: bridge
